--- 
abstract: Catalyst based application
author: J. Shirley,,,
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: STV
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Action::REST: 0.60
  Catalyst::Action::RenderView: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7011
  Catalyst::View::Email: 0
  Catalyst::View::TT: 0
  DateTime: 0
  DateTime::Format::DateManip: 0
  DateTime::Format::MySQL: 0
  DateTime::Format::Pg: 0
  DateTime::Format::RSS: 0
  JSON::DWIW: 0
  JSON::Syck: 0
  YAML: 0
  YAML::Syck: 1.00
version: 0.01002
